fix: fail to read whole WAL in some circumstances
This is a regression test for a case where I called
`read` instead of `read_exact` in KVRecord to read
the header of a WAL entry. After 11397 records (of
a particular size, as below, presumably), `read`
consistently didn't read the whole header even though
it was in the file. The way the error case was written
caused this to stop reading the file but not report
an error to the caller.

Unclear why the read returned fewer bytes at this
exact point, but using `read_exact` will continue
reading if it has an error. Presumably there was a
page fault or something that caused `read` to return
early.

I happened to spot this during benchmarking where I was
trying out different wal write threshold values.

Git commit where this was found: e751a95 but it was
lurking ever since the WAL was written.

This was the trace from the benchmark in examples/bench.rs:

Replayed 0 records from WAL. nextseq=0.
Running open() took 0.303ms.
Writing sstable took 20ms.
Running write() took 121ms.
Running read() 23900 times took 942ms (0.039ms per read).
Replayed 11397 records from WAL. nextseq=11397.
thread 'main' panicked at examples/bench.rs:58:17:
called `Option::unwrap()` on a `None` value